config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :users, only: [:new, :create, :show], param: :username

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates_presence_of :title, :artist
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true,
                       uniqueness: true

  enum role: %w(default admin)
  has_many :songs
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :most_recent_song, :current_user

  def most_recent_song
      @song ||= Song.find(session[:most_recent_song_id]) if session[:most_recent_song_id]
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to login_path
      flash[:invalid_login] = "Invalid Login"
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Bye bye!"
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update] # ==> allows you to delete lines in show, edit, update methods, will call set_song before doing anything else in these methods

  def index
    @songs_index = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      session[:most_recent_song_id] = @song.id
      redirect_to songs_path
      flash[:notice] = "Song created!"
    else
      flash[:errors] = @song.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      flash.now[:errors] = @song.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    Song.destroy(params[:id])
    # song = Song.find(params[:id])
    # song.destroy ==> this will also work, maybe use this when you might be affecting another table
    redirect_to songs_path
  end

  private

  def set_song # ==> pulling out repeated code below:
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
      flash[:new_user] = "You've successfully registered"
    else
      flash.now[:error] = "Try again. Username and Password are required"
      render :new
    end
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if current_user %>
      Welcome, <%= current_user.username %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", login_path %>
    <% end %>
  </div>

  <p>
    <strong>Newest song:</strong> <%#= most_recent_song.title %>
  </p>

  <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "flash_#{type}" %>
    <% end %>

  <%= yield %>
  <br></br>
  <%= link_to "New Song", new_song_path %> |
  <%= link_to "Song Index", songs_path %>
</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%=  f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist %>
  <%= f.text_field :artist %><br>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<h1>Songs Index</h1>

<% @songs_index.each do |song| %>
  <li>
    <%= link_to song.title, song %>
    <%= link_to "Edit", edit_song_path(song) %>
    <%= link_to "Delete", song, method: :delete %>
  </li>
<% end %>
<br></br>

app/views/songs/new.html.erb
<h1>Add A New Song</h1>

<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<h2><%= @song.artist %></h2>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= form_for(User.new) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<p>Welcome, <%= current_user.username %>!</p>